version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 25
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 25
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 25
  return-statements:
    config:
      threshold: 10
  similar-code:
    enabled: false # language-specific defaults. an override will affect all languages.
  identical-code:
    enabled: false # language-specific defaults. an override will affect all languages.
