language: node_js

node_js:
  - 13.13.0

services:
  - postgresql

addons:
  code_climate:
    repo_token:
      secure: "D0TXQTy8aSN/1UGGGyF8paj2JR6X3OHbhylVZ8OoVWEGGsV4f88lHoCQwGPGFuAIq+GqZsc8YV/KikqIah6J7NFG2pYFkByRln+vVmDiO3TD2JrwUSNUTE0b+yi/DYoKWRDNKEnUZ7Puv4yeO0/qExzWsOixdS0FggMO7mtl+dUSTwRDMjHUjo06LPlSPgarBzEx1ULvH7WPAFBygFslypSHmtYGx9xR6ArjxFzW0IbVOT91TQusWuvyBQSLuqrVkwO6XbVXHM+0Tk+5Vng78reCS77y2qdFVT8tLGU3ySfOn5jvi25jWmDmYXmrMr102vSqB5EDi4/x2do7y3qr6uKuo11vt1t9OHZHu63EFzgcRJ3oIe6xIpbb+frpjhkksZNqrPSDW3rkFfugxm3xqG/DCggGIvQq5nBdbAmrQ7Wm86ecBXNQAzoPqjv1uWsLAqvavwRhKYjBm6aP7V1j/e/WWx2l88gJWUgEew8/7wfrv8x836UCCaKm1oaOgA+bko6RLz5A0v7Cpi4EXyprdsikMkR41ml6xXQj/PYbsDJ5OB4EHJI/X5EJjHIQo0f6vNdFlscJa1mQvs9ydHMz8JqHrVEpDR/oWqf1kUdIMx8nD9RDjduvhv5vtdjw1IhJQZ9jcFygG3UaW6RHG9hCFS0TepruhR1sfmNHs8NMOPE="
      
before_script:
  - psql -c "create database phonehistorystore_db_test;" -U postgres

install:
  - yarn

script:
  - yarn test
 
notification:
  - email: false

after_success:
  - yarn run coverage
